application:
  default_host: ~
  default_from: ~

analytics:
  web_property_id: ~

contact:
  email: ~

s3:
  upload_bucket: ~

import:
  access_token: ~
  repo: waynegraham/dlme-metadata
  properties:
    exhibit_slug: library
  sources:
    penn_tei:
      directory: manuscript/records/penn/schoenberg
      traject_file: tei_config
      properties:
        inst_id: penn
    stanford_mods:
      directory: maps/records/stanford
      traject_file: mods_config
      properties:
        inst_id: stanford
    met_csv:
      directory: museum/records
      traject_file: met_csv_config
